# Generated by Django 5.2.7 on 2025-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=35, verbose_name='Роль'),
        ),
    ]
