# Generated by Django 5.2.7 on 2025-10-19 13:10

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_user_alter_recipe_user_alter_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='html_description',
            field=tinymce.models.HTMLField(default=2, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(help_text='Добавить рецепт может только шеф-повар', limit_choices_to={'type': 'user_type_chef'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
