# Generated by Django 5.2.7 on 2025-10-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('user_type_chef', 'Шеф-повар'), ('user_type_culinary_enthusiast', 'любитель кулинарии')], max_length=35, verbose_name='Роль'),
        ),
    ]
