# Generated by Django 5.2.7 on 2025-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_options_recipe_html_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='raiting',
            field=models.IntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
