# Generated by Django 5.2.7 on 2025-10-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=70, null=True, verbose_name='Название')),
                ('ingredients', models.TextField(verbose_name='ингредиенты')),
                ('steps', models.TextField(verbose_name='Шаги')),
                ('time_cooking', models.TimeField(verbose_name='время приготовления')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
