# Generated by Django 5.2.7 on 2025-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_recipe_options_user_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_email',
            field=models.JSONField(blank=True, default=dict, verbose_name='код-подтвердение email'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_confirmed_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтвердения email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed_email',
            field=models.BooleanField(default=False, verbose_name='Подтвердение email'),
        ),
    ]
