# Generated by Django 5.2.7 on 2025-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_confirmation_email_user_date_confirmed_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная учетная запись'),
        ),
    ]
