# Generated by Django 5.2.7 on 2025-11-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория рецепта', 'verbose_name_plural': 'Категории рецептов'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ManyToManyField(to='main.recipe', verbose_name='Рецепт'),
        ),
    ]
