# Generated by Django 5.2.7 on 2025-11-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_options_alter_recipecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
