# Generated by Django 4.2 on 2025-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_comment_recipe_comment_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('text', models.TextField(max_length=250, verbose_name='Описание')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Обращение в техподдержку',
                'verbose_name_plural': 'Обращения в техподдержку',
            },
        ),
    ]
