# Generated by Django 5.2.7 on 2025-11-22 10:32

from django.db import migrations, models

def add_initial_recipe_categories(apps, schema_editor):
    RecipeCategory = apps.get_model('main', 'RecipeCategory')
    initial_categories = [
        'Завтрак',
        'Обед', 
        'Ужин',
        'Десерт'
    ]
    
    for category_title in initial_categories:
        RecipeCategory.objects.get_or_create(title=category_title)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории'),
        ),
        migrations.RunPython(
            add_initial_recipe_categories,
            reverse_code=migrations.RunPython.noop
        ),
    ]
