# Generated by Django 5.2.7 on 2025-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_recipecategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecategory',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название категории'),
        ),
    ]
