class CodesErrors:
    UNKNOWN_VALIDATION_ERROR = 4000
    USER_NOT_FOUND = 4004
    NOT_FOUND = 40044

    ERROR_EMAIL = 4001
    ERROR_PASSWORD = 4002
    ERROR_EMAIL_OR_PHONE = 4003
    ERROR_EMAIL_OR_PHONE_OR_PASSWORD = 4004
    ERROR_SEND_CONFIRMATION_CODE = 4005
    ERROR_NOT_VALID_CONFIRMATION_CODE = 4007
    ERROR_ACCOUNT_ALREADY_ACTIVATED = 4008
    AUTHENTICATION_FAILED = 4011
   

KEY_USER_TYPE_CHEF = 'user_type_chef'
KEY_USER_TYPE_CULINARY_ENTHUSIAST = 'user_type_culinary_enthusiast'

KEY_USER_TYPES_CHOICES = (
    (KEY_USER_TYPE_CHEF, 'Шеф-повар'),
    (KEY_USER_TYPE_CULINARY_ENTHUSIAST, 'Любитель кулинарии'),
)

KEY_RAITING_RECIPE_VERY_BAD = 1
KEY_RAITING_RECIPE_BAD = 2
KEY_RAITING_RECIPE_SATISFACTORY = 3
KEY_RAITING_RECIPE_GOOD = 4
KEY_RAITING_RECIPE_EXCELLENT = 5

RATING_RECIPE_CHOICES = [
    (KEY_RAITING_RECIPE_VERY_BAD, 'Очень плохо'),
    (KEY_RAITING_RECIPE_BAD, 'Плохо'),
    (KEY_RAITING_RECIPE_SATISFACTORY, 'Удовлетворительно'),
    (KEY_RAITING_RECIPE_GOOD, 'Хорошо'),
    (KEY_RAITING_RECIPE_EXCELLENT, 'Отлично'),
]
