KEY_USER_TYPE_CHEF = 'user_type_chef'
KEY_USER_TYPE_CULINARY_ENTHUSIAST = 'user_type_culinary_enthusiast'

KEY_USER_TYPES_CHOICES = (
    (KEY_USER_TYPE_CHEF, 'Шеф-повар'),
    (KEY_USER_TYPE_CULINARY_ENTHUSIAST, 'Любитель кулинарии'),
)

KEY_RAITING_RECIPE_VERY_BAD = 1
KEY_RAITING_RECIPE_BAD = 2
KEY_RAITING_RECIPE_SATISFACTORY = 3
KEY_RAITING_RECIPE_GOOD = 4
KEY_RAITING_RECIPE_EXCELLENT = 5

RATING_RECIPE_CHOICES = [
    (KEY_RAITING_RECIPE_VERY_BAD, 'Очень плохо'),
    (KEY_RAITING_RECIPE_BAD, 'Плохо'),
    (KEY_RAITING_RECIPE_SATISFACTORY, 'Удовлетворительно'),
    (KEY_RAITING_RECIPE_GOOD, 'Хорошо'),
    (KEY_RAITING_RECIPE_EXCELLENT, 'Отлично'),
]
